### ISSUE TITLE
Fix git cloning always requiring a password and failing the first time through

### ISSUE THREAD

**Issue by AntonSlooten** [Aeronavics/ValleyForge#8]

**Comment by JamesMorritt** [comment]
Fixed in #10

**Comment by AntonSlooten** [comment]
Oh? Thats good. Just git pulling in a non git directory asks for a password?

**Comment by JamesMorritt** [comment]
it was in the cumulus directory, so a git pull required a password as cumulus is password protected

**Comment by JamesMorritt** [comment]
whereas it should be in the submodule directory
